src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Negotiating</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Merchandise__c</fullName>
        <label>Merchandise</label>
        <referenceTo>Merchandise__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{0000}</displayFormat>
        <label>Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Merchandise__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <description>Category of Merchandise</description>
        <label>Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Notebooks</fullName>
                    <default>true</default>
                    <label>Notebooks</label>
                </value>
                <value>
                    <fullName>Monitors</fullName>
                </value>
                <value>
                    <fullName>Keyboards</fullName>
                </value>
                <value>
                    <fullName>Mouses</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Picture__c</fullName>
        <description>Picture of Merchandise</description>
        <label>Picture</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Merchandise</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MerchController.cls
/**
 * Created by Serhii on 24.10.2018.
 */

public with sharing class MerchController {
//main controller of web shop
    @AuraEnabled
    public static List<Merchandise__c> getMerchandises() {
        String[] fieldsToCheck = new String[]{
                'Id', 'Name', 'Picture__c', 'Category__c', 'Description__c',
                'Price__c', 'Quantity__c'
        };

        Map<String, Schema.SObjectField> fieldDescribeTokens =
                Schema.SObjectType.Merchandise__c.fields.getMap();

        for (String field : fieldsToCheck) {
            if (!fieldDescribeTokens.get(field).getDescribe().isAccessible()) {
                throw new System.NoAccessException();
            }
        }
        return [
                SELECT Id, Name, Picture__c, Category__c, Description__c,
                        Price__c, Quantity__c
                FROM Merchandise__c
        ];
    }

    @AuraEnabled
    public static List<Merchandise__c> getNotes() {
        String categoryString = 'Notebooks';
        return getCategory(categoryString);
    }

    @AuraEnabled
    public static List<Merchandise__c> getMons() {
        String categoryString = 'Monitors';
        return getCategory(categoryString);
    }
    @AuraEnabled
    public static List<Merchandise__c> getKes() {
        String categoryString = 'Keyboards';
        return getCategory(categoryString);
    }
    @AuraEnabled
    public static List<Merchandise__c> getMouses() {
        String categoryString = 'Mouses';
        return getCategory(categoryString);
    }

    public static List<Merchandise__c> getCategory(String categoryString) {
// Check to make sure all fields are accessible to this user
        String[] fieldsToCheck = new String[]{
                'Id', 'Name', 'Picture__c', 'Category__c', 'Description__c',
                'Price__c', 'Quantity__c'
        };
        Map<String, Schema.SObjectField> fieldDescribeTokens =
                Schema.SObjectType.Merchandise__c.fields.getMap();
        for (String field : fieldsToCheck) {
            if (!fieldDescribeTokens.get(field).getDescribe().isAccessible()) {
                throw new System.NoAccessException();
            }
        }
        return [
                SELECT Id, Name, Picture__c, Category__c, Description__c,
                        Price__c, Quantity__c
                FROM Merchandise__c
                WHERE Category__c = :categoryString
        ];
    }
    @AuraEnabled
    public static void createInvoice(List <Merchandise__c> merchandises) {
        if (merchandises.size() > 0) {
            Invoice__c inv = new Invoice__c(Status__c = 'Open');
            insert inv;
            System.debug('Invoice__c id ' + inv.id);
            List <Invoice_Line_Item__c> lineItems = new List<Invoice_Line_Item__c>();
            for (Merchandise__c merch : merchandises) {
                if (merch.Quantity__c > 0 && merch.Quantity__c != null) {
                    Invoice_Line_Item__c item = new Invoice_Line_Item__c(Invoice__c = inv.id,
                            Merchandise__c = merch.id, Quantity__c = merch.Quantity__c, Unit_Price__c = merch.Price__c);
                    lineItems.add(item);
                    System.debug('Invoice_Line_Item__c' + item);
                }
            }
            insert lineItems;
            upsert inv;
        }
    }
}