src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Total__c</fullName>
        <description>общая цена для всего Заказа</description>
        <label>Invoice Total</label>
        <summarizedField>Invoice_Line_Item__c.Total__c</summarizedField>
        <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Negotiating</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DelinvoiceExt.cls
/*
 * Created by Serhii on 27.10.2018.
 */
public with sharing class DelinvoiceExt {
//in invoice record detail dell all button
    @AuraEnabled
    public static void delAll() {
        System.debug('delAll');
        List<Invoice__c> invoiceList = [SELECT ID FROM Invoice__c];
        try {
            delete invoiceList;
        } catch (Exception ex)
        {
            throw new AuraHandledException(ex.getMessage());
        }
    }

    @AuraEnabled
    public static List<Invoice__c> getInvs() {
        String[] fieldsToCheck = new String[]{
                'Id', 'Name', 'Status__c', 'Invoice_Total__c', 'Description__c'
                };

        Map<String, Schema.SObjectField> fieldDescribeTokens =
                Schema.SObjectType.Invoice__c.fields.getMap();

        for (String field : fieldsToCheck) {
            if (!fieldDescribeTokens.get(field).getDescribe().isAccessible()) {
                throw new System.NoAccessException();
            }
        }
        return [
                SELECT Id, Name, Status__c, Invoice_Total__c, Description__c
                FROM Invoice__c
        ];
    }
}