src/objects/Invoice__c.object
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Merchandise__c</fullName>
        <label>Merchandise</label>
        <referenceTo>Merchandise__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{0000}</displayFormat>
        <label>Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Merchandise__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <description>Category of Merchandise</description>
        <label>Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Notebooks</fullName>
                    <default>true</default>
                    <label>Notebooks</label>
                </value>
                <value>
                    <fullName>Monitors</fullName>
                </value>
                <value>
                    <fullName>Keyboards</fullName>
                </value>
                <value>
                    <fullName>Mouses</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Merchandise</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MerchControllerTest.cls
@isTest
public class MerchControllerTest {

    static void newMerch() {
        List<Merchandise__c> merchList = new List<Merchandise__c>(4);
        String[] categ = new String[4];
        categ[0] = 'Keyboards';
        categ[1] = 'Monitors';
        categ[2] = 'Mouses';
        categ[3] = 'Notebooks';
        for (Integer i = 0; i < 4; i++) {
            merchList[i] = new Merchandise__c(Name = 'TestMerch' + i, Category__c = categ[i], Quantity__c = i);
        }
        insert merchList;
    }

    @isTest static void TestGetMerchandises() {
        newMerch();
        Merchandise__c[] merchList = MerchController.getMerchandises();
        System.assertEquals(merchList.isEmpty(), false);
    }


    @isTest static void TestGetNotes() {
        newMerch();
        Merchandise__c[] merchList = MerchController.getNotes();
        System.assertEquals(merchList.isEmpty(), false);
        System.assertEquals(merchList[0].Category__c, 'Notebooks');
    }

    @isTest static void TestgetMons() {
        newMerch();
        Merchandise__c[] merchList = MerchController.getMons();
        System.assertEquals(merchList.isEmpty(), false);
        System.assertEquals(merchList[0].Category__c, 'Monitors');
    }

    @isTest static void TestgetKes() {
        newMerch();
        Merchandise__c[] merchList = MerchController.getKes();
        System.assertEquals(merchList.isEmpty(), false);
        System.assertEquals(merchList[0].Category__c, 'Keyboards');
    }

    @isTest static void TestgetMouses() {
        newMerch();
        Merchandise__c[] merchList = MerchController.getMouses();
        System.assertEquals(merchList.isEmpty(), false);
        System.assertEquals(merchList[0].Category__c, 'Mouses');
    }

    @isTest static void TestCreateInvoice() {
        newMerch();
        Merchandise__c[] merchList = MerchController.getMerchandises();
        MerchController.createInvoice(merchList);
        List<Invoice_Line_Item__c> ili = [SELECT Invoice__c, Merchandise__c, Quantity__c FROM Invoice_Line_Item__c ];
        for (Integer i = 0; i < 3; i++) {
            System.assertEquals(ili[i].Quantity__c, i + 1);
            System.assertEquals(ili[i].Merchandise__c, merchList[i + 1].id);
        }
    }


}