src/objects/Merchandise__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <description>Category of Merchandise</description>
        <label>Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Notebooks</fullName>
                    <default>true</default>
                    <label>Notebooks</label>
                </value>
                <value>
                    <fullName>Monitors</fullName>
                </value>
                <value>
                    <fullName>Keyboards</fullName>
                </value>
                <value>
                    <fullName>Mouses</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Merchandise</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MerchQuanTest.cls
@isTest
public class MerchQuanTest {
    @isTest static void quantityDecreased() {
        Merchandise__c merch = new Merchandise__c (Category__c = 'Mouses', Name = 'TestMerch', Quantity__c = 20);
        insert merch;
        // Perform test
        Test.startTest();
        merch.Quantity__c -= 19;
        update merch;
        Test.stopTest();
        // Verify
        merch = [SELECT Quantity__c FROM Merchandise__c WHERE Name='TestMerch' LIMIT 1];
        System.assertEquals(6, merch.Quantity__c);
    }

}